#!/bin/bash
# validate (or not)  files to PDF/A-4 or PDF/A-4F
# assumes verapdf script or bat file is in the path

cd pdf20

# PDF/A-4F  (10 files)
for i in \
2401.05361v1-tagged.pdf \
2401.09436v1-tagged.pdf \
2401.09965v1-tagged.pdf \
Sample-AF-Math-LaTeX.pdf \
amsldoc-tagged.pdf \
mathml-AF-ex1.pdf \
mathml-AF-ex2.pdf \
47464-t-tagged.pdf \
5250A-23-group-theory.pdf \
PHY-exam.pdf
do
echo ""
echo "======================"
echo $i
echo "----------------------"
verapdf  -f 4f $i 2>&1 | grep -E "errorMessage|validationReport " | sort | uniq
echo ""
echo "======================"
echo ""
done

# PDF/A-4 (6 files)
for i in \
macbeth-tagged.pdf \
pdfa-art.pdf \
pg17161-tagged.pdf \
tagpdf.pdf \
tb139mitt-deims24.pdf \
bible.pdf
do
echo ""
echo "======================"
echo $i
echo "----------------------"
verapdf  -f 4 $i 2>&1 | grep -E "errorMessage|validationReport " | sort | uniq
echo ""
echo "======================"
echo ""
done


